#ifndef PROJECT_EULER_COMMON_PERMUTATION_GENERATOR_H_
#define PROJECT_EULER_COMMON_PERMUTATION_GENERATOR_H_

namespace PROJECT_EULER {
	namespace COMMON {
		
	};
};

#endif // PROJECT_EULER_COMMON_PERMUTATION_GENERATOR_H_
